# GitHub Sponsors + Ko-fi button — shows on every repo page
# Activates the "Sponsor" button at the top of meeko-nerve-center
github: [meekotharaccoon-cell]
ko_fi: meekotharaccoon
custom: ['https://meekotharaccoon-cell.github.io/meeko-nerve-center/revenue.html']
