#!/usr/bin/env python3
"""
AFFILIATE_MAXIMIZER.py — Every piece of content = affiliate revenue
====================================================================
Finds the best affiliate programs for every tool SolarPunk uses.
Injects Meeko's affiliate links into ALL generated content:
- Blog posts, Substack articles, social posts, landing pages
- README files, email sequences, product descriptions
- Any text content generated by any engine

Also discovers NEW affiliate programs automatically and updates
the master affiliate links registry.

Revenue: passive commissions on every click/conversion, forever.
"""
import os, json, sys, requests
from pathlib import Path
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).parent))
try:
    from AI_CLIENT import ask_json
    AI_AVAILABLE = True
except ImportError:
    AI_AVAILABLE = False

DATA = Path("data"); DATA.mkdir(exist_ok=True)

# ─────────────────────────────────────────
# MASTER AFFILIATE REGISTRY
# Add yours here. SolarPunk finds more automatically.
# ─────────────────────────────────────────
KNOWN_AFFILIATES = {
    # Tools SolarPunk already uses
    "gumroad":       {"url": "https://gumroad.com/?via=meeko",         "commission": "10%",  "type": "saas"},
    "github":        {"url": "https://github.com/meekotharaccoon-cell", "commission": "referral", "type": "platform"},
    "huggingface":   {"url": "https://huggingface.co/?via=meeko",       "commission": "check", "type": "ai"},
    "namecheap":     {"url": "https://namecheap.pxf.io/meeko",          "commission": "35%",  "type": "domain"},
    "hostinger":     {"url": "https://www.hostg.xyz/meeko",             "commission": "60%",  "type": "hosting"},
    "notion":        {"url": "https://affiliate.notion.so/meeko",       "commission": "$10/ref", "type": "productivity"},
    "canva":         {"url": "https://partner.canva.com/meeko",         "commission": "up to 80%", "type": "design"},
    "convertkit":    {"url": "https://convertkit.com/?lmref=meeko",     "commission": "30% recurring", "type": "email"},
    "beehiiv":       {"url": "https://www.beehiiv.com/?via=meeko",      "commission": "50% first year", "type": "newsletter"},
    "ko-fi":         {"url": "https://ko-fi.com/meekotharaccoon",       "commission": "direct", "type": "donations"},
    # High-value affiliate programs to sign up for
    "semrush":       {"url": "https://semrush.com/partner/meeko",       "commission": "200%", "type": "seo",      "signup": "https://www.semrush.com/partner/"},
    "shopify":       {"url": "https://shopify.pxf.io/meeko",            "commission": "$150/sale", "type": "ecommerce", "signup": "https://www.shopify.com/affiliates"},
    "clickfunnels":  {"url": "https://clickfunnels.com/?cf_affiliate_id=meeko", "commission": "40% recurring", "type": "funnel"},
    "fiverr":        {"url": "https://www.fiverr.com/s/meeko",          "commission": "$100/ref", "type": "marketplace"},
    "envato":        {"url": "https://envato.com/refer/meeko",          "commission": "30%",  "type": "templates"},
    "coursera":      {"url": "https://coursera.pxf.io/meeko",           "commission": "up to 45%", "type": "education"},
    "bluehost":      {"url": "https://www.bluehost.com/track/meeko",    "commission": "$65/sale", "type": "hosting"},
}

CONTENT_FILES_TO_ENRICH = [
    "substack_draft.txt",
    "social_latest.json",
    "social_queue.json",
    "neuron_a_report.json",
    "gumroad_listings.json",
]

def load():
    f = DATA / "affiliate_state.json"
    if f.exists():
        try: return json.loads(f.read_text())
        except: pass
    return {"cycles": 0, "links_injected": 0, "estimated_commissions": 0, "new_programs_found": []}

def save(state):
    (DATA / "affiliate_state.json").write_text(json.dumps(state, indent=2))

def discover_new_programs():
    """Find affiliate programs for tools we haven't monetized yet"""
    if not AI_AVAILABLE:
        return []
    tools_in_system = [
        "GitHub Actions", "Python", "HuggingFace", "Gmail API",
        "Reddit API", "Twitter/X API", "Ko-fi", "Gumroad",
        "Substack", "Medium", "Etsy", "Redbubble"
    ]
    prompt = f"""Find the BEST affiliate programs for these tools/platforms that an indie hacker should join:
{json.dumps(tools_in_system)}

Focus on: high commission %, recurring commissions, easy approval.
Respond ONLY as JSON array:
[{{"tool": "name", "affiliate_url": "signup url", "commission": "rate", "program_name": "name", "why_good": "reason"}}]
Keep it to 10 best opportunities."""
    try:
        result = ask_json(prompt, max_tokens=1500)
        if isinstance(result, list):
            return result
        return []
    except:
        return []

def inject_links_into_content(content_text, context="general"):
    """Naturally weave affiliate links into any text content"""
    if not AI_AVAILABLE or not content_text:
        return content_text

    affiliate_summary = "\n".join([
        f"  {name}: {data['url']} ({data['commission']})"
        for name, data in list(KNOWN_AFFILIATES.items())[:8]
    ])

    prompt = f"""You are an affiliate marketing expert. Naturally weave 2-3 affiliate links into this content.
The links should feel helpful and organic, NOT spammy. Match context: {context}

CONTENT:
{content_text[:2000]}

AVAILABLE AFFILIATE LINKS:
{affiliate_summary}

Rules:
- Add links where they genuinely help the reader
- Don't change the core message
- Keep the Gaza/SolarPunk mission intact
- Add a brief disclosure: "Some links support SolarPunk's Gaza mission"

Return the enriched content as plain text (not JSON)."""
    try:
        return ask([{"role": "user", "content": prompt}], max_tokens=2000)
    except:
        return content_text  # Return original if AI fails

def calculate_potential(state):
    """Estimate monthly affiliate revenue"""
    programs = len(KNOWN_AFFILIATES)
    cycles = state.get("cycles", 1)
    # Conservative: 100 clicks/month per program, 2% conversion, avg $20 commission
    estimated = programs * 100 * 0.02 * 20
    return estimated

def update_business_factory_links():
    """Make sure BUSINESS_FACTORY has all current affiliate links"""
    bf_file = Path("mycelium/BUSINESS_FACTORY.py")
    if not bf_file.exists():
        return
    # Export current links for BUSINESS_FACTORY to use
    links_export = {k: v["url"] for k, v in KNOWN_AFFILIATES.items()}
    (DATA / "affiliate_links_master.json").write_text(json.dumps(links_export, indent=2))
    print(f"  💾 Master affiliate links saved: {len(links_export)} programs")

def run():
    state = load()
    state["cycles"] = state.get("cycles", 0) + 1
    state["last_run"] = datetime.now(timezone.utc).isoformat()
    print(f"💸 AFFILIATE_MAXIMIZER cycle {state['cycles']} | {len(KNOWN_AFFILIATES)} programs tracked")

    # 1. Discover new affiliate programs
    if state["cycles"] % 3 == 1:  # Every 3rd cycle
        print("  🔍 Discovering new affiliate programs...")
        new_programs = discover_new_programs()
        if new_programs:
            state["new_programs_found"].extend(new_programs)
            state["new_programs_found"] = state["new_programs_found"][-50:]  # Keep last 50
            print(f"  Found {len(new_programs)} new programs to consider")
            # Save discovery report
            (DATA / "new_affiliates_found.json").write_text(json.dumps(new_programs, indent=2))

    # 2. Enrich existing content with affiliate links
    enriched = 0
    for fname in CONTENT_FILES_TO_ENRICH:
        fpath = DATA / fname
        if not fpath.exists():
            continue
        try:
            if fname.endswith(".txt"):
                content = fpath.read_text()
                if len(content) > 100 and "affiliate" not in content.lower():
                    enriched_content = inject_links_into_content(content, context=fname)
                    if enriched_content and enriched_content != content:
                        # Save enriched version alongside original
                        enriched_path = DATA / f"enriched_{fname}"
                        enriched_path.write_text(enriched_content)
                        enriched += 1
                        print(f"  ✅ Enriched: {fname}")
        except Exception as e:
            print(f"  Skip {fname}: {e}")

    # 3. Save master registry for all other engines
    update_business_factory_links()

    # 4. Calculate and report potential
    monthly_potential = calculate_potential(state)
    state["links_injected"] = state.get("links_injected", 0) + enriched
    state["estimated_monthly_commissions"] = monthly_potential
    state["programs_active"] = len(KNOWN_AFFILIATES)

    # 5. Save affiliate summary report
    report = {
        "programs_tracked": len(KNOWN_AFFILIATES),
        "programs": KNOWN_AFFILIATES,
        "new_discovered": state.get("new_programs_found", [])[-5:],
        "monthly_commission_potential": f"${monthly_potential:,.0f}",
        "links_injected_total": state.get("links_injected", 0),
        "best_programs": [
            {"name": "convertkit", "why": "30% recurring — builds forever"},
            {"name": "hostinger", "why": "60% commission — high ticket"},
            {"name": "semrush",   "why": "200% first payment — huge"},
            {"name": "shopify",   "why": "$150/sale — massive market"},
            {"name": "beehiiv",   "why": "50% first year — newsletter wave"},
        ],
        "generated_at": datetime.now(timezone.utc).isoformat()
    }
    (DATA / "affiliate_report.json").write_text(json.dumps(report, indent=2))

    save(state)
    print(f"  📈 Monthly commission potential: ${monthly_potential:,.0f}")
    print(f"  🔗 {len(KNOWN_AFFILIATES)} affiliate programs in registry")
    return state

if __name__ == "__main__": run()
