import os
import re

def build_entirety():
    mutation_path = 'data/synergy_mutations.txt'
    toolbox_path = 'mycelium/SWARM_TOOLBOX.py'
    project_dir = os.path.join('projects', 'Active_Synthesis')
    
    if not os.path.exists(mutation_path): return
    if not os.path.exists(project_dir): os.makedirs(project_dir)

    try:
        with open(mutation_path, 'r', encoding='utf-8') as f:
            mutations = [m for m in f.read().split('--- NEW SYNERGY MUTATION ---') if m.strip()]
            mutation = mutations[-1]

        needed_skills = re.findall(r'\[SKILL\]: def (\w+)', mutation)
        
        logic_bridge = f"""
# --- AUTO-GENERATED BY THE ARCHITECT ---
import sys
import os
sys.path.append(os.path.abspath('../../mycelium'))
try:
    from SWARM_TOOLBOX import *
except ImportError:
    pass

def run_manifestation():
    print("🚀 Initializing Manifestation Logic...")
    try:
        # Executing detected skills
        {chr(10).join(["        " + s + "()" for s in needed_skills]) if needed_skills else "        pass"}
    except Exception as e:
        print(f"⚠️ Logic Gap: {e}")
        with open('../../data/self_builder_queue.json', 'a') as q:
            import json
            q.write(json.dumps({{"task": "HEAL", "target": "projects/Active_Synthesis/main.py", "error": str(e)}}) + "\n")

if __name__ == "__main__":
    run_manifestation()
"""
        with open(os.path.join(project_dir, 'main.py'), 'w', encoding='utf-8') as f:
            f.write(logic_bridge)
        print(f"🏗️ Architect: Logic bridge established in {project_dir}")

    except Exception as e:
        print(f"🏗️ Architect Error: {e}")

if __name__ == "__main__":
    build_entirety()
