import os
import re

def build_entirety():
    mutation_path = 'data/synergy_mutations.txt'
    toolbox_path = 'mycelium/SWARM_TOOLBOX.py'
    project_dir = os.path.join('projects', 'Active_Synthesis')
    
    if not os.path.exists(mutation_path): return
    if not os.path.exists(project_dir): os.makedirs(project_dir)

    # 1. Read the Blueprint
    with open(mutation_path, 'r', encoding='utf-8') as f:
        mutation = f.read().split('--- NEW SYNERGY MUTATION ---')[-1]

    # 2. Extract needed 'Skills' from the Toolbox
    needed_skills = re.findall(r'\[SKILL\]: def (\w+)', mutation)
    
    # 3. Build the 'Main.py' by importing from the Toolbox
    logic_bridge = f"""
# --- AUTO-GENERATED BY THE ARCHITECT ---
import sys
import os
sys.path.append(os.path.abspath('../../mycelium'))
from SWARM_TOOLBOX import *

def run_manifestation():
    print("🚀 Initializing Manifestation Logic...")
    # Attempting to call discovered legacy skills
    try:
        {" ".join([skill + "()" for skill in needed_skills])}
    except Exception as e:
        print(f"⚠️ Logic Gap Found: {e}")
        # Signal the Auto-Healer to intervene
        with open('../../data/self_builder_queue.json', 'a') as q:
            q.write(f'{{"task": "HEAL", "target": "projects/Active_Synthesis/main.py", "error": "{str(e)}"}}' + "\\n")

if __name__ == "__main__":
    run_manifestation()
"""
    
    with open(os.path.join(project_dir, 'main.py'), 'w', encoding='utf-8') as f:
        f.write(logic_bridge)
        
    print(f"🏗️ Auto-Architect: Full project logic manifested in {project_dir}")

if __name__ == "__main__":
    build_entirety()
